### ISSUE TITLE
Paytm Problem

### ISSUE THREAD

**Issue by PrernaBhavsar99** [PrernaBhavsar99/experiments#7]

**Comment by Rohit19060** [comment]
Testing Mark 1

**Comment by risheetajain** [comment]
testing issue's

**Comment by Rohit19060** [comment]
Paytm is not working in Flutter

**Comment by Rohit19060** [comment]
@shivkanyawaman4 She knows how to do that

**Comment by risheetajain** [comment]
it will work from  [#allinsdk]('7737366393' `)

**Comment by Rohit19060** [comment]
Reopened not needed @PrernaBhavsar99 already knows this
